-- ============================================
-- IMPORTAZIONE GIOCATORI DA LISTONE FANTAPAZZ
-- Esegui nel SQL Editor di Supabase
-- ============================================

-- Aggiunge la colonna quotazione se non esiste
ALTER TABLE players ADD COLUMN IF NOT EXISTS quotazione INTEGER DEFAULT 0;

-- Inserisce tutti i giocatori
INSERT INTO players (name, role, serie_a_team, quotazione) VALUES
  ('Carnesecchi', 'P', 'Atalanta', 13),
  ('Butez', 'P', 'Como', 13),
  ('Skorupski', 'P', 'Bologna', 11),
  ('De Gea', 'P', 'Fiorentina', 11),
  ('Maignan', 'P', 'Milan', 10),
  ('Di Gregorio', 'P', 'Juventus', 10),
  ('Milinkovic', 'P', 'Napoli', 10),
  ('Sommer', 'P', 'Inter', 9),
  ('Motta', 'P', 'Lazio', 8),
  ('Meret', 'P', 'Napoli', 7),
  ('Svilar', 'P', 'Roma', 7),
  ('Okoye', 'P', 'Udinese', 7),
  ('Perin', 'P', 'Juventus', 7),
  ('Corvi', 'P', 'Parma', 6),
  ('Provedel', 'P', 'Lazio', 5),
  ('Paleari', 'P', 'Torino', 5),
  ('Muric', 'P', 'Sassuolo', 5),
  ('Falcone', 'P', 'Lecce', 4),
  ('Bijlow', 'P', 'Genoa', 4),
  ('Suzuki', 'P', 'Parma', 3),
  ('Montipo', 'P', 'Verona', 3),
  ('Caprile', 'P', 'Cagliari', 3),
  ('Audero', 'P', 'Cremonese', 3),
  ('Ravaglia', 'P', 'Bologna', 2),
  ('Leali', 'P', 'Genoa', 1),
  ('Turati', 'P', 'Sassuolo', 1),
  ('Semper', 'P', 'Pisa', 1),
  ('Christensen', 'P', 'Fiorentina', 1),
  ('Ciocci', 'P', 'Cagliari', 1),
  ('Di Gennaro', 'P', 'Inter', 1),
  ('Fruchtl', 'P', 'Lecce', 1),
  ('Furlanetto', 'P', 'Lazio', 1),
  ('Gollini', 'P', 'Roma', 1),
  ('Martinez J.', 'P', 'Inter', 1),
  ('Padelli', 'P', 'Udinese', 1),
  ('Perilli', 'P', 'Verona', 1),
  ('Pinsoglio', 'P', 'Juventus', 1),
  ('Rinaldi', 'P', 'Parma', 1),
  ('Rossi Fr.', 'P', 'Atalanta', 1),
  ('Russo A.', 'P', 'Sassuolo', 1),
  ('Samooja', 'P', 'Lecce', 1),
  ('Satalino', 'P', 'Sassuolo', 1),
  ('Sava', 'P', 'Udinese', 1),
  ('Scuffet', 'P', 'Pisa', 1),
  ('Siegrist', 'P', 'Genoa', 1),
  ('Sommariva', 'P', 'Genoa', 1),
  ('Sportiello', 'P', 'Atalanta', 1),
  ('Terracciano', 'P', 'Milan', 1),
  ('Torriani', 'P', 'Milan', 1),
  ('Vigorito', 'P', 'Como', 1),
  ('Contini', 'P', 'Napoli', 1),
  ('Nicolas', 'P', 'Pisa', 1),
  ('Nava', 'P', 'Cremonese', 1),
  ('Zelezny', 'P', 'Roma', 1),
  ('Israel', 'P', 'Torino', 1),
  ('Pessina M.', 'P', 'Bologna', 1),
  ('Sgarbi', 'P', 'Como', 1),
  ('Lezzerini', 'P', 'Fiorentina', 1),
  ('Nunziante', 'P', 'Udinese', 1),
  ('Silvestri', 'P', 'Cremonese', 1),
  ('Menke', 'P', 'Como', 1),
  ('Toniolo', 'P', 'Verona', 1),
  ('Cavlina', 'P', 'Como', 1),
  ('Ferrante', 'P', 'Napoli', 1),
  ('Zacchi', 'P', 'Sassuolo', 1),
  ('Malovec', 'P', 'Cremonese', 1),
  ('Calligaris', 'P', 'Inter', 1),
  ('Castagnini', 'P', 'Verona', 1),
  ('Pittarella', 'P', 'Milan', 1),
  ('Mangiapoco', 'P', 'Juventus', 1),
  ('Taho', 'P', 'Inter', 1),
  ('Happonen', 'P', 'Bologna', 1),
  ('Scaglia S.', 'P', 'Juventus', 1),
  ('Lysionok', 'P', 'Genoa', 1),
  ('Penev', 'P', 'Lecce', 1),
  ('Auseklis', 'P', 'Cagliari', 1),
  ('Sherri', 'P', 'Cagliari', 1),
  ('Tornqvist', 'P', 'Como', 1),
  ('Casentini', 'P', 'Parma', 1),
  ('Siviero', 'P', 'Torino', 1),
  ('Guizzo', 'P', 'Pisa', 1),
  ('Luppichini', 'P', 'Pisa', 1),
  ('Leonardelli', 'P', 'Fiorentina', 1),
  ('Giacomone', 'P', 'Lazio', 1),
  ('Franceschelli', 'P', 'Bologna', 1),
  ('Pardel', 'P', 'Atalanta', 1),
  ('Dimarco', 'D', 'Inter', 36),
  ('Bremer', 'D', 'Juventus', 22),
  ('Ndicka', 'D', 'Roma', 17),
  ('Kalulu', 'D', 'Juventus', 16),
  ('Pavlovic', 'D', 'Milan', 16),
  ('Mancini', 'D', 'Roma', 15),
  ('Zappacosta', 'D', 'Atalanta', 15),
  ('Ostigard', 'D', 'Genoa', 15),
  ('Delprato', 'D', 'Parma', 14),
  ('Spinazzola', 'D', 'Napoli', 14),
  ('Palestra', 'D', 'Cagliari', 14),
  ('Akanji', 'D', 'Inter', 14),
  ('Dodo', 'D', 'Fiorentina', 13),
  ('Kempf', 'D', 'Como', 13),
  ('Wesley', 'D', 'Roma', 13),
  ('Dumfries', 'D', 'Inter', 12),
  ('Buongiorno', 'D', 'Napoli', 12),
  ('Gosens', 'D', 'Fiorentina', 12),
  ('Bastoni A.', 'D', 'Inter', 11),
  ('Carlos Augusto', 'D', 'Inter', 11),
  ('Solet', 'D', 'Udinese', 11),
  ('Cambiaso', 'D', 'Juventus', 11),
  ('Bisseck', 'D', 'Inter', 11),
  ('De Winter', 'D', 'Milan', 11),
  ('Gallo', 'D', 'Lecce', 11),
  ('Celik', 'D', 'Roma', 11),
  ('Lucumi', 'D', 'Bologna', 10),
  ('Marusic', 'D', 'Lazio', 10),
  ('Vojvoda', 'D', 'Como', 10),
  ('Kabasele', 'D', 'Udinese', 10),
  ('Diego Carlos', 'D', 'Como', 10),
  ('Tavares', 'D', 'Lazio', 9),
  ('Zortea', 'D', 'Bologna', 9),
  ('Beukema', 'D', 'Napoli', 9),
  ('Gila', 'D', 'Lazio', 9),
  ('Martin', 'D', 'Genoa', 9),
  ('Caracciolo', 'D', 'Pisa', 9),
  ('Kelly', 'D', 'Juventus', 9),
  ('Scalvini', 'D', 'Atalanta', 9),
  ('Muharemovic', 'D', 'Sassuolo', 9),
  ('Ramon', 'D', 'Como', 9),
  ('Bernasconi', 'D', 'Atalanta', 9),
  ('Garcia', 'D', 'Sassuolo', 9),
  ('Djimsiti', 'D', 'Atalanta', 8),
  ('Luperto', 'D', 'Cremonese', 8),
  ('Vasquez', 'D', 'Genoa', 8),
  ('Maripan', 'D', 'Torino', 8),
  ('Ranieri', 'D', 'Fiorentina', 8),
  ('Miranda J.', 'D', 'Bologna', 8),
  ('Valeri', 'D', 'Parma', 8),
  ('Kristensen T.', 'D', 'Udinese', 8),
  ('Norton Cuffy', 'D', 'Genoa', 8),
  ('Frese', 'D', 'Verona', 8),
  ('Gutierrez', 'D', 'Napoli', 8),
  ('Acerbi', 'D', 'Inter', 7),
  ('Kolasinac', 'D', 'Atalanta', 7),
  ('Mina', 'D', 'Cagliari', 7),
  ('Pongracic', 'D', 'Fiorentina', 7),
  ('Romagnoli A.', 'D', 'Lazio', 7),
  ('Tomori', 'D', 'Milan', 7),
  ('Vitik', 'D', 'Bologna', 7),
  ('Valle', 'D', 'Como', 7),
  ('Barbieri', 'D', 'Cremonese', 7),
  ('Parisi', 'D', 'Fiorentina', 7),
  ('Bartesaghi', 'D', 'Milan', 7),
  ('Gabriel', 'D', 'Lecce', 7),
  ('Marcandalli', 'D', 'Genoa', 7),
  ('Idzes', 'D', 'Sassuolo', 7),
  ('Troilo', 'D', 'Parma', 7),
  ('Britschgi', 'D', 'Parma', 7),
  ('Bellanova', 'D', 'Atalanta', 6),
  ('Hien', 'D', 'Atalanta', 6),
  ('Olivera', 'D', 'Napoli', 6),
  ('Ismajli', 'D', 'Torino', 6),
  ('Kamara', 'D', 'Udinese', 6),
  ('Coco', 'D', 'Torino', 6),
  ('Van der Brempt', 'D', 'Como', 6),
  ('Canestrelli', 'D', 'Pisa', 6),
  ('Rensch', 'D', 'Roma', 6),
  ('Valenti', 'D', 'Parma', 6),
  ('Moreno A.', 'D', 'Como', 6),
  ('Pedersen', 'D', 'Torino', 6),
  ('Oyegoke', 'D', 'Verona', 6),
  ('Veiga D.', 'D', 'Lecce', 6),
  ('Provstgaard', 'D', 'Lazio', 6),
  ('Joao Mario', 'D', 'Bologna', 6),
  ('Walukiewicz', 'D', 'Sassuolo', 6),
  ('Athekame', 'D', 'Milan', 6),
  ('Nelsson', 'D', 'Verona', 6),
  ('Obrador', 'D', 'Torino', 6),
  ('Di Lorenzo', 'D', 'Napoli', 5),
  ('Rrahmani', 'D', 'Napoli', 5),
  ('Ghilardi', 'D', 'Roma', 5),
  ('Doig', 'D', 'Sassuolo', 5),
  ('Obert', 'D', 'Cagliari', 5),
  ('Calabresi', 'D', 'Pisa', 5),
  ('Hermoso', 'D', 'Roma', 5),
  ('Bradaric', 'D', 'Verona', 5),
  ('Siebert', 'D', 'Lecce', 5),
  ('Ze Pedro', 'D', 'Cagliari', 5),
  ('Edmundsson', 'D', 'Verona', 5),
  ('Angelino', 'D', 'Roma', 4),
  ('Comuzzo', 'D', 'Fiorentina', 4),
  ('Zappa', 'D', 'Cagliari', 4),
  ('Patric', 'D', 'Lazio', 4),
  ('Angori', 'D', 'Pisa', 4),
  ('Circati', 'D', 'Parma', 4),
  ('Dossena', 'D', 'Cagliari', 4),
  ('Ebosse', 'D', 'Torino', 4),
  ('Idrissi', 'D', 'Cagliari', 4),
  ('Pezzella', 'D', 'Cremonese', 4),
  ('Tsimikas', 'D', 'Roma', 4),
  ('Coulibaly', 'D', 'Sassuolo', 4),
  ('Gabbia', 'D', 'Milan', 3),
  ('Gatti', 'D', 'Juventus', 3),
  ('Lazaro', 'D', 'Torino', 3),
  ('Ehizibue', 'D', 'Udinese', 3),
  ('Bertola', 'D', 'Udinese', 3),
  ('Zemura', 'D', 'Udinese', 3),
  ('Bianchetti', 'D', 'Cremonese', 3),
  ('Estupinan', 'D', 'Milan', 3),
  ('Belghali', 'D', 'Verona', 3),
  ('Gaspar', 'D', 'Lecce', 2),
  ('Holm', 'D', 'Juventus', 2),
  ('Baschirotto', 'D', 'Cremonese', 2),
  ('Juan Jesus', 'D', 'Napoli', 2),
  ('Terracciano F.', 'D', 'Cremonese', 2),
  ('Sabelli', 'D', 'Genoa', 2),
  ('Valentini', 'D', 'Verona', 2),
  ('Romagna', 'D', 'Sassuolo', 2),
  ('Smolcic', 'D', 'Como', 2),
  ('Zanoli', 'D', 'Udinese', 2),
  ('Kossounou', 'D', 'Atalanta', 2),
  ('Heggem', 'D', 'Bologna', 2),
  ('Rodriguez Ju.', 'D', 'Cagliari', 2),
  ('Albiol', 'D', 'Pisa', 2),
  ('Mlacic', 'D', 'Udinese', 2),
  ('Biraghi', 'D', 'Torino', 1),
  ('Pellegrini Lu.', 'D', 'Lazio', 1),
  ('Ahanor', 'D', 'Atalanta', 1),
  ('Darmian', 'D', 'Inter', 1),
  ('De Vrij', 'D', 'Inter', 1),
  ('Felici', 'D', 'Cagliari', 1),
  ('Lazzari', 'D', 'Lazio', 1),
  ('Ceccherini', 'D', 'Cremonese', 1),
  ('Hysaj', 'D', 'Lazio', 1),
  ('Lykogiannis', 'D', 'Bologna', 1),
  ('De Silvestri', 'D', 'Bologna', 1),
  ('Floriani', 'D', 'Cremonese', 1),
  ('Fortini', 'D', 'Fiorentina', 1),
  ('Gigot', 'D', 'Lazio', 1),
  ('Marianucci', 'D', 'Torino', 1),
  ('Bakker', 'D', 'Atalanta', 1),
  ('Cabal', 'D', 'Juventus', 1),
  ('Folino', 'D', 'Cremonese', 1),
  ('Jean', 'D', 'Lecce', 1),
  ('Mazzocchi', 'D', 'Napoli', 1),
  ('Pieragnolo', 'D', 'Sassuolo', 1),
  ('Casale', 'D', 'Bologna', 1),
  ('Corradi', 'D', 'Verona', 1),
  ('Otoa', 'D', 'Genoa', 1),
  ('Scott', 'D', 'Lecce', 1),
  ('Slotsager', 'D', 'Verona', 1),
  ('Goldaniga', 'D', 'Como', 1),
  ('Sazonov', 'D', 'Torino', 1),
  ('Perez M.', 'D', 'Lecce', 1),
  ('Kospo', 'D', 'Fiorentina', 1),
  ('Denoon', 'D', 'Pisa', 1),
  ('Ndaba', 'D', 'Lecce', 1),
  ('Rugani', 'D', 'Fiorentina', 1),
  ('Ndiaye', 'D', 'Parma', 1),
  ('Cuadrado', 'D', 'Pisa', 1),
  ('Cande', 'D', 'Sassuolo', 1),
  ('Pintus', 'D', 'Cagliari', 1),
  ('Fallou', 'D', 'Verona', 1),
  ('Kouadio', 'D', 'Fiorentina', 1),
  ('Bella Kotchap', 'D', 'Verona', 1),
  ('Ziolkowski', 'D', 'Roma', 1),
  ('Lamptey', 'D', 'Fiorentina', 1),
  ('Nkounkou', 'D', 'Torino', 1),
  ('Odogu', 'D', 'Milan', 1),
  ('Faye M.', 'D', 'Cremonese', 1),
  ('Obric', 'D', 'Atalanta', 1),
  ('Coppola', 'D', 'Pisa', 1),
  ('Alexiou', 'D', 'Inter', 1),
  ('Pedro Felipe', 'D', 'Sassuolo', 1),
  ('Scaglia F.', 'D', 'Juventus', 1),
  ('Kumer Celik', 'D', 'Genoa', 1),
  ('Cocchi', 'D', 'Inter', 1),
  ('Maye', 'D', 'Inter', 1),
  ('Conde B.', 'D', 'Parma', 1),
  ('Cogoni', 'D', 'Cagliari', 1),
  ('Pellini', 'D', 'Torino', 1),
  ('Arizala', 'D', 'Udinese', 1),
  ('Bozhinov', 'D', 'Pisa', 1),
  ('Drobnic', 'D', 'Parma', 1),
  ('Helland', 'D', 'Bologna', 1),
  ('Lirola', 'D', 'Verona', 1),
  ('De Battisti', 'D', 'Verona', 1),
  ('Jakirovic', 'D', 'Inter', 1),
  ('Zatterstrom', 'D', 'Genoa', 1),
  ('Balbo', 'D', 'Fiorentina', 1),
  ('Carboni F.', 'D', 'Parma', 1),
  ('De Paoli', 'D', 'Como', 1),
  ('Raterink', 'D', 'Cagliari', 1),
  ('Kamate', 'D', 'Inter', 1),
  ('Pavesi', 'D', 'Cremonese', 1),
  ('Doucoure', 'D', 'Genoa', 1),
  ('Mena Martinez', 'D', 'Parma', 1),
  ('Navarro', 'D', 'Atalanta', 1),
  ('Yildiz', 'C', 'Juventus', 50),
  ('Mctominay', 'C', 'Napoli', 38),
  ('Paz', 'C', 'Como', 38),
  ('Modric', 'C', 'Milan', 30),
  ('Mckennie', 'C', 'Juventus', 29),
  ('Calhanoglu', 'C', 'Inter', 28),
  ('Vlasic', 'C', 'Torino', 26),
  ('Pulisic', 'C', 'Milan', 25),
  ('Barella', 'C', 'Inter', 24),
  ('Politano', 'C', 'Napoli', 24),
  ('Thuram K.', 'C', 'Juventus', 24),
  ('Zielinski', 'C', 'Inter', 24),
  ('Conceicao', 'C', 'Juventus', 24),
  ('Da Cunha', 'C', 'Como', 23),
  ('Caqueret', 'C', 'Como', 22),
  ('Fagioli', 'C', 'Fiorentina', 22),
  ('Thorstvedt', 'C', 'Sassuolo', 22),
  ('Baturina', 'C', 'Como', 22),
  ('Malinovskyi', 'C', 'Genoa', 22),
  ('Rabiot', 'C', 'Milan', 22),
  ('Isaksen', 'C', 'Lazio', 21),
  ('Casadei', 'C', 'Torino', 21),
  ('Perrone', 'C', 'Como', 21),
  ('Taylor', 'C', 'Lazio', 21),
  ('Boga', 'C', 'Juventus', 21),
  ('De Ketelaere', 'C', 'Atalanta', 20),
  ('Fofana', 'C', 'Milan', 20),
  ('Atta', 'C', 'Udinese', 20),
  ('Ekkelenkamp', 'C', 'Udinese', 20),
  ('Frendrup', 'C', 'Genoa', 20),
  ('Pasalic', 'C', 'Atalanta', 20),
  ('Pellegrini Lo.', 'C', 'Roma', 20),
  ('Coulibaly L.', 'C', 'Lecce', 20),
  ('Kone I.', 'C', 'Sassuolo', 20),
  ('Mandragora', 'C', 'Fiorentina', 19),
  ('Rodriguez J.', 'C', 'Como', 19),
  ('Zaniolo', 'C', 'Udinese', 19),
  ('Ederson', 'C', 'Atalanta', 18),
  ('Mkhitaryan', 'C', 'Inter', 18),
  ('De Roon', 'C', 'Atalanta', 18),
  ('Ricci', 'C', 'Milan', 18),
  ('Cataldi', 'C', 'Lazio', 18),
  ('Karlstrom', 'C', 'Udinese', 18),
  ('Bernardeschi', 'C', 'Bologna', 18),
  ('Rowe', 'C', 'Bologna', 18),
  ('Lobotka', 'C', 'Napoli', 17),
  ('Locatelli', 'C', 'Juventus', 17),
  ('Cristante', 'C', 'Roma', 17),
  ('Saelemaekers', 'C', 'Milan', 17),
  ('Zalewski', 'C', 'Atalanta', 17),
  ('Vandeputte', 'C', 'Cremonese', 17),
  ('Santos', 'C', 'Napoli', 17),
  ('Zaccagni', 'C', 'Lazio', 16),
  ('Odgaard', 'C', 'Bologna', 16),
  ('Kone M.', 'C', 'Roma', 16),
  ('Bernabe', 'C', 'Parma', 16),
  ('Thorsby', 'C', 'Cremonese', 16),
  ('Aebischer', 'C', 'Pisa', 16),
  ('Leris', 'C', 'Pisa', 16),
  ('Cambiaghi', 'C', 'Bologna', 15),
  ('Tramoni', 'C', 'Pisa', 15),
  ('Ellertsson', 'C', 'Genoa', 15),
  ('Matic', 'C', 'Sassuolo', 15),
  ('Elmas', 'C', 'Napoli', 15),
  ('De Bruyne', 'C', 'Napoli', 14),
  ('Gaetano', 'C', 'Cagliari', 14),
  ('Sucic', 'C', 'Inter', 14),
  ('Keita', 'C', 'Parma', 14),
  ('NDour', 'C', 'Fiorentina', 14),
  ('Gandelman', 'C', 'Lecce', 14),
  ('Harrison', 'C', 'Fiorentina', 14),
  ('Freuler', 'C', 'Bologna', 13),
  ('Strefezza', 'C', 'Parma', 13),
  ('Adopo', 'C', 'Cagliari', 13),
  ('Luis Henrique', 'C', 'Inter', 13),
  ('Pisilli', 'C', 'Roma', 13),
  ('Ramadani', 'C', 'Lecce', 13),
  ('Messias', 'C', 'Genoa', 13),
  ('Samardzic', 'C', 'Atalanta', 13),
  ('Solomon', 'C', 'Fiorentina', 13),
  ('Loftus Cheek', 'C', 'Milan', 12),
  ('Oristanio', 'C', 'Parma', 12),
  ('Loyola', 'C', 'Pisa', 12),
  ('Zaragoza', 'C', 'Roma', 12),
  ('Miretti', 'C', 'Juventus', 11),
  ('Mazzitelli', 'C', 'Cagliari', 11),
  ('Neres', 'C', 'Napoli', 10),
  ('Frattesi', 'C', 'Inter', 10),
  ('Koopmeiners', 'C', 'Juventus', 10),
  ('Brescianini', 'C', 'Fiorentina', 10),
  ('Bernede', 'C', 'Verona', 10),
  ('Piotrowski', 'C', 'Udinese', 10),
  ('Sorensen', 'C', 'Parma', 10),
  ('Zhegrova', 'C', 'Juventus', 10),
  ('Anguissa', 'C', 'Napoli', 9),
  ('Ferguson', 'C', 'Bologna', 9),
  ('Fabbian', 'C', 'Fiorentina', 9),
  ('Kuhn', 'C', 'Como', 8),
  ('Dele Bashiru', 'C', 'Lazio', 8),
  ('Payero', 'C', 'Cremonese', 8),
  ('Sohm', 'C', 'Bologna', 8),
  ('Maldini', 'C', 'Lazio', 8),
  ('Prati', 'C', 'Torino', 8),
  ('Sottil', 'C', 'Lecce', 8),
  ('Fadera', 'C', 'Sassuolo', 8),
  ('Moro', 'C', 'Bologna', 8),
  ('Jashari', 'C', 'Milan', 8),
  ('Nicolussi', 'C', 'Parma', 8),
  ('Ondrejka', 'C', 'Parma', 7),
  ('Dominguez B.', 'C', 'Bologna', 7),
  ('Serdar', 'C', 'Verona', 7),
  ('Gineitis', 'C', 'Torino', 7),
  ('Sergi Roberto', 'C', 'Como', 7),
  ('Sulemana I.', 'C', 'Cagliari', 7),
  ('Lipani', 'C', 'Sassuolo', 7),
  ('Miller', 'C', 'Udinese', 7),
  ('Akpa Akpro', 'C', 'Verona', 7),
  ('Gagliardini', 'C', 'Verona', 7),
  ('Anjorin', 'C', 'Torino', 6),
  ('Rovella', 'C', 'Lazio', 6),
  ('Gilmour', 'C', 'Napoli', 6),
  ('Estevez', 'C', 'Parma', 6),
  ('Folorunsho', 'C', 'Cagliari', 6),
  ('Zerbin', 'C', 'Cremonese', 6),
  ('Harroui', 'C', 'Verona', 6),
  ('Grassi', 'C', 'Cremonese', 6),
  ('El Aynaoui', 'C', 'Roma', 6),
  ('Ilkhan', 'C', 'Torino', 6),
  ('Suslov', 'C', 'Verona', 5),
  ('Baldanzi', 'C', 'Genoa', 5),
  ('Piccinini G.', 'C', 'Pisa', 5),
  ('Volpato', 'C', 'Sassuolo', 5),
  ('Vergara', 'C', 'Napoli', 5),
  ('Ngom', 'C', 'Lecce', 5),
  ('Lovric', 'C', 'Verona', 4),
  ('Deiola', 'C', 'Cagliari', 4),
  ('Kostic', 'C', 'Juventus', 4),
  ('Musah', 'C', 'Atalanta', 4),
  ('Marin M.', 'C', 'Pisa', 4),
  ('Ordonez', 'C', 'Parma', 4),
  ('Toure I.', 'C', 'Pisa', 4),
  ('Hojholt', 'C', 'Pisa', 4),
  ('Maleh', 'C', 'Cremonese', 4),
  ('Pobega', 'C', 'Bologna', 4),
  ('Aboukhlal', 'C', 'Torino', 4),
  ('Diouf', 'C', 'Inter', 4),
  ('Vranckx', 'C', 'Sassuolo', 4),
  ('Stengs', 'C', 'Pisa', 4),
  ('Amorim', 'C', 'Genoa', 4),
  ('Bakola', 'C', 'Sassuolo', 4),
  ('El Shaarawy', 'C', 'Roma', 3),
  ('Niasse', 'C', 'Verona', 3),
  ('Basic', 'C', 'Lazio', 3),
  ('Fazzini', 'C', 'Fiorentina', 2),
  ('Collocolo', 'C', 'Cremonese', 2),
  ('Ilic', 'C', 'Torino', 2),
  ('Zarraga', 'C', 'Udinese', 2),
  ('Bondo', 'C', 'Cremonese', 2),
  ('Venturino', 'C', 'Roma', 2),
  ('Akinsamiro', 'C', 'Pisa', 2),
  ('Al Musrati', 'C', 'Verona', 2),
  ('Fofana S.', 'C', 'Lecce', 2),
  ('Przyborek', 'C', 'Lazio', 2),
  ('Belahyane', 'C', 'Lazio', 1),
  ('Boloca', 'C', 'Sassuolo', 1),
  ('Helgason', 'C', 'Lecce', 1),
  ('Addai', 'C', 'Como', 1),
  ('Berisha', 'C', 'Lecce', 1),
  ('Masini', 'C', 'Genoa', 1),
  ('Njie', 'C', 'Torino', 1),
  ('Adzic', 'C', 'Juventus', 1),
  ('Iannoni', 'C', 'Sassuolo', 1),
  ('Marchwinski', 'C', 'Lecce', 1),
  ('Perciun', 'C', 'Torino', 1),
  ('Tameze', 'C', 'Torino', 1),
  ('Vural', 'C', 'Pisa', 1),
  ('Munoz', 'C', 'Lazio', 1),
  ('Pyyhtia', 'C', 'Bologna', 1),
  ('Liteta', 'C', 'Cagliari', 1),
  ('Cuenca', 'C', 'Genoa', 1),
  ('Sabiri', 'C', 'Fiorentina', 1),
  ('Kovac', 'C', 'Lecce', 1),
  ('Gorter', 'C', 'Lecce', 1),
  ('Plicco', 'C', 'Parma', 1),
  ('Sala A.', 'C', 'Lecce', 1),
  ('Lorran', 'C', 'Pisa', 1),
  ('Onana', 'C', 'Genoa', 1),
  ('Cremaschi', 'C', 'Parma', 1),
  ('Cornet', 'C', 'Genoa', 1),
  ('Bonsignori', 'C', 'Como', 1),
  ('Ciardi', 'C', 'Parma', 1),
  ('Lickunas', 'C', 'Cremonese', 1),
  ('Sala E.', 'C', 'Milan', 1),
  ('Bettazzi', 'C', 'Pisa', 1),
  ('Farcomeni', 'C', 'Lazio', 1),
  ('Acquah', 'C', 'Torino', 1),
  ('Camara A.', 'C', 'Udinese', 1),
  ('Prisco', 'C', 'Napoli', 1),
  ('Scarlato', 'C', 'Parma', 1),
  ('De Chiara', 'C', 'Napoli', 1),
  ('Licina', 'C', 'Juventus', 1),
  ('Iling Jr.', 'C', 'Pisa', 1),
  ('Lahdo', 'C', 'Como', 1),
  ('Topalovic', 'C', 'Inter', 1),
  ('Lafont G.', 'C', 'Genoa', 1),
  ('Malfitano', 'C', 'Cagliari', 1),
  ('Sulev', 'C', 'Cagliari', 1),
  ('Frangella', 'C', 'Sassuolo', 1),
  ('Martinez L.', 'A', 'Inter', 48),
  ('Thuram', 'A', 'Inter', 36),
  ('Krstovic', 'A', 'Atalanta', 35),
  ('Hojlund', 'A', 'Napoli', 34),
  ('Malen', 'A', 'Roma', 34),
  ('Douvikas', 'A', 'Como', 31),
  ('Esposito S.', 'A', 'Cagliari', 31),
  ('Davis', 'A', 'Udinese', 31),
  ('Esposito Pio', 'A', 'Inter', 31),
  ('Castro', 'A', 'Bologna', 29),
  ('Adams', 'A', 'Torino', 29),
  ('Lauriente', 'A', 'Sassuolo', 29),
  ('Nkunku', 'A', 'Milan', 28),
  ('Leao', 'A', 'Milan', 27),
  ('Berardi', 'A', 'Sassuolo', 27),
  ('Pinamonti', 'A', 'Sassuolo', 27),
  ('Pellegrino', 'A', 'Parma', 26),
  ('Simeone', 'A', 'Torino', 26),
  ('David', 'A', 'Juventus', 25),
  ('Piccoli', 'A', 'Fiorentina', 25),
  ('Scamacca', 'A', 'Atalanta', 25),
  ('Vitinha', 'A', 'Genoa', 25),
  ('Kean', 'A', 'Fiorentina', 24),
  ('Bonny', 'A', 'Inter', 24),
  ('Soule', 'A', 'Roma', 24),
  ('Colombo', 'A', 'Genoa', 24),
  ('Vardy', 'A', 'Cremonese', 24),
  ('Orsolini', 'A', 'Bologna', 22),
  ('Gudmundsson', 'A', 'Fiorentina', 22),
  ('Raspadori', 'A', 'Atalanta', 22),
  ('Moreo', 'A', 'Pisa', 22),
  ('Bonazzoli', 'A', 'Cremonese', 22),
  ('Orban', 'A', 'Verona', 22),
  ('Zapata', 'A', 'Torino', 21),
  ('Dybala', 'A', 'Roma', 19),
  ('Fullkrug', 'A', 'Milan', 18),
  ('Pedro', 'A', 'Lazio', 16),
  ('Giovane', 'A', 'Napoli', 16),
  ('Dia', 'A', 'Lazio', 15),
  ('Kilicsoy', 'A', 'Cagliari', 15),
  ('Openda', 'A', 'Juventus', 15),
  ('Vaz', 'A', 'Roma', 15),
  ('Dovbyk', 'A', 'Roma', 14),
  ('Diao', 'A', 'Como', 14),
  ('Stulic', 'A', 'Lecce', 14),
  ('Banda', 'A', 'Lecce', 13),
  ('Ekuban', 'A', 'Genoa', 13),
  ('Dallinga', 'A', 'Bologna', 12),
  ('Ferguson E.', 'A', 'Roma', 12),
  ('Ratkov', 'A', 'Lazio', 12),
  ('Kulenovic', 'A', 'Torino', 12),
  ('Pierotti', 'A', 'Lecce', 11),
  ('Noslin', 'A', 'Lazio', 11),
  ('Bowie', 'A', 'Verona', 11),
  ('Lukaku', 'A', 'Napoli', 10),
  ('Gimenez', 'A', 'Milan', 10),
  ('Djuric', 'A', 'Cremonese', 10),
  ('Morata', 'A', 'Como', 10),
  ('Buksa', 'A', 'Udinese', 10),
  ('Vlahovic', 'A', 'Juventus', 9),
  ('Sulemana K.', 'A', 'Atalanta', 9),
  ('Ekhator', 'A', 'Genoa', 9),
  ('Sarr', 'A', 'Verona', 8),
  ('Cancellieri', 'A', 'Lazio', 8),
  ('Durosinmi', 'A', 'Pisa', 8),
  ('Stojilkovic', 'A', 'Pisa', 7),
  ('Borrelli', 'A', 'Cagliari', 6),
  ('Frigan', 'A', 'Parma', 6),
  ('Moumbagna', 'A', 'Cremonese', 6),
  ('Meister', 'A', 'Pisa', 5),
  ('Okereke', 'A', 'Cremonese', 5),
  ('Nzola', 'A', 'Sassuolo', 4),
  ('Cheddira', 'A', 'Lecce', 4),
  ('Elphege', 'A', 'Parma', 4),
  ('Pavoletti', 'A', 'Cagliari', 3),
  ('Sanabria', 'A', 'Cremonese', 3),
  ('Mosquera', 'A', 'Verona', 2),
  ('Camarda', 'A', 'Lecce', 2),
  ('NDri', 'A', 'Lecce', 2),
  ('Almqvist', 'A', 'Parma', 1),
  ('Belotti', 'A', 'Cagliari', 1),
  ('Moro L.', 'A', 'Sassuolo', 1),
  ('Milik', 'A', 'Juventus', 1),
  ('Bayo', 'A', 'Udinese', 1),
  ('Ajayi', 'A', 'Verona', 1),
  ('Arena A.', 'A', 'Roma', 1),
  ('Balentien', 'A', 'Milan', 1),
  ('Gueye', 'A', 'Udinese', 1),
  ('Camara', 'A', 'Atalanta', 1),
  ('Vermesan', 'A', 'Verona', 1),
  ('Cardinali', 'A', 'Parma', 1),
  ('Lavelli', 'A', 'Inter', 1),
  ('Mosconi', 'A', 'Inter', 1),
  ('Castiello', 'A', 'Milan', 1),
  ('Fernandes S.', 'A', 'Lazio', 1),
  ('Trepy', 'A', 'Cagliari', 1),
  ('Elimoghale', 'A', 'Juventus', 1),
  ('Serra', 'A', 'Lazio', 1),
  ('Anghele', 'A', 'Juventus', 1),
  ('Isaac', 'A', 'Verona', 1),
  ('Nuredini', 'A', 'Genoa', 1),
  ('Albarracin', 'A', 'Cagliari', 1),
  ('Braschi', 'A', 'Fiorentina', 1),
  ('Gabellini', 'A', 'Torino', 1),
  ('Oboavwoduo', 'A', 'Juventus', 1),
  ('Mikolajewski', 'A', 'Parma', 1),
  ('Mendy', 'A', 'Cagliari', 1),
  ('Castaldo', 'A', 'Bologna', 1),
  ('Faye N.', 'A', 'Cremonese', 1)
ON CONFLICT DO NOTHING;

-- Totale giocatori importati: 613
SELECT COUNT(*) as totale_giocatori FROM players;
